(PDS-556) Updates to the select component
puppetlabs/design-system pull request #352
Opened 2020-10-30 16:53 UTC by Lukeaber

What has been added/changed:
- A description can be added to each list item
- A new button at the bottom of the select dropdown called the navigationbutton has been added, this has it's own callback and label prop
- A new type of select "text select" has been added. This is for use when the select is a title of subtitle of a page. 
- Grouping a select list can now be done by simply passing an object into the options prop instead of an array
- The select target is now using the design systems own button component to render the text select.

2020-12-10 01:14 UTC, chrisleicester requested changes
This is really great work. Adds a ton of new functionality to our select component.

I have a handful of suggestions/change requests. Feel free to ping me directly on slack if you disagree with any of my comments, or just if you want to chat about some of the implementation suggestions I mentioned.

2020-12-10 01:14 UTC, chrisleicester commented on packages/react-components/source/react/internal/option-menu-list/OptionMenuList.js
> +                  isDescriptionMenu={isDescriptionMenu}
Again, unnecessary as I pointed out above.

2020-12-10 01:14 UTC, chrisleicester commented on packages/react-components/source/react/internal/option-menu-list/OptionMenuList.js
> +        {navigationButton && (
This `render` method is getting pretty long. You might create a new method called `renderNavigationMenu` like:

`{navigationButton && renderNavigationButton()}`

or, if you ditch the navigationButton boolean:

`{navigationLabel && renderNavigationButton()}`

2020-12-10 01:14 UTC, chrisleicester commented on packages/react-components/source/react/internal/option-menu-list/OptionMenuListItem.js
> +  description: PropTypes.string,
Again, only need the `description` prop.

2020-12-10 01:14 UTC, chrisleicester commented on packages/react-components/source/react/library/select/SelectTarget.js
> +      </Button>
Here we do 3 separate boolean checks for `type === textselect`. I think we should just create two different elements based on `type === textselect` and pass it into the jsx:

```
let divContents = null;
if (type === 'textelect') {
    divContents = <>yourNewTextSelectStuff</>
} else {
    divContents = <>existingdivContenst</>
}

return <div>{divContents}</div>
```

This way its _really_ hard for a future dev to mess up the boolean logic when modifying the code.

2021-04-22 15:35 UTC, vine77 commented
This PR is stale as of about 6 months ago, so closing as review comments haven't been addressed. Please feel free to reopen!

2021-04-22 15:35 UTC, closed without merging