Add Accessibility docs
puppetlabs/design-system pull request #581
Opened 2022-06-23 19:43 UTC by vine77

### Description of proposed changes

Add "Accessibility Guide" docs, sourced from [the Google Doc](https://docs.google.com/document/d/1G02Q9muByvByX9QoWUxhmW9FUw4SWVHSdzNp6yRKeRo/edit?usp=sharing).

### Screenshot of proposed changes

<img width="1456" alt="Screen Shot 2022-06-23 at 12 36 58 PM" src="https://user-images.githubusercontent.com/175123/175383124-b1d128d6-7e3d-4dad-a5a0-610b486e9f2d.png">

2022-06-24 17:34 UTC, steveax requested changes
Looks great, thanks! Left some comments around skipped heading levels.

https://www.w3.org/WAI/tutorials/page-structure/headings/

2022-06-28 15:22 UTC, vine77 commented on packages/design-system-website/foundations/Accessibility.md
> +## Why is accessibility important?
With Styleguidist, there ends up being an `h1` at the top generated from the config: https://github.com/puppetlabs/design-system/pull/581/files#diff-517a792e222ff0a45abde8f1d3e9db9e408eda423b5a3f615a51db843035fdb9R83

So in this PR at the moment it says "Accessibility Guide". ("Accessibility" might be simpler. 🙂)

2022-06-29 15:39 UTC, SaysKez commented on packages/design-system-website/foundations/Accessibility.md
> +#### Accessible design helps everyone, including people with:
Fixed! Thanks for pointing that out, Steve,

2022-06-29 15:40 UTC, SaysKez approved these changes
Updated the headings to avoid skipping a level and h1 will be generated from the config so looks like we're good to go. Thanks!

2022-06-29 19:21 UTC, merged