(CDPE-6574) Align Authentication title element with Figma design
puppetlabs/design-system pull request #660
Opened 2024-03-25 11:06 UTC by petergmurphy

### Description of proposed changes

- Changed the Authentication title from a `h5` to a `h3` element.
- This modification ensures consistency with the Figma design documentation's styling.

### Screenshot of proposed changes

2024-03-25 18:05 UTC, sean-mckenna requested changes

2024-03-25 18:05 UTC, sean-mckenna commented on CHANGELOG.md
> +- [Logo] Change the title of the Authentication component from a `h5` to a `h3` element. (by [@petergmurphy](https://github.com/petergmurphy))
You can probably combine this into one changelog statement

```suggestion
- [Authentication] description here. (by [@petergmurphy](https://github.com/petergmurphy))
```

2024-03-25 18:09 UTC, sean-mckenna commented
Does this render the new cd4pe logo when the product prop is `continuous-delivery`?

2024-03-26 09:44 UTC, petergmurphy commented
Seems to render the new cd4pe product logo fine when I run the server locally:

![image](https://github.com/puppetlabs/design-system/assets/57573942/248db9a1-3197-4f99-ba2e-0751105a684b)

2024-03-28 12:23 UTC, sean-mckenna approved these changes

2024-03-28 12:38 UTC, merged